lr: 1e-5
init_epoch: 0
epochs: 50
test_epoch: 50
restore: false
gpu_id: 0
is_debug: no
feat_dim: 2883
name: 'coarse_mvp2m'
save_path: 'results_ocrtoc'
data_root: '/local-scratch6/rakesh/meshmvs_ocrtoc_dataset_full'
